name: scrape-appointmenttrader

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node setup (no npm cache; remove lockfile requirement headaches)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Restore state file (matches scraper's STATE_FILE = state.v1.json)
      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: state.v1.json
          key: state-v1-${{ github.ref_name }}
          restore-keys: |
            state-v1-

      - name: Install deps
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FIRST_RUN: "false"    # set to "false" after the first successful seed
          SEED_IF_EMPTY: "true"
          DEBUG_LOG: "1"       # optional; remove later
        run: npm run scrape

      # Save updated state so future runs dedupe correctly
      - name: Save state cache
        uses: actions/cache@v4
        with:
          path: state.v1.json
          key: state-v1-${{ github.run_id }}
          restore-keys: |
            state-v1-
